app:
  name: rai
  verbose: false
  debug: false
aws:
  access_key_id: ==AES32==+NPjNiwCtTNvMUg94O/PVGOPc1N6ExBx7Lyz3TGRuIqVfqFoYuRNEl1gkZw=
  secret_access_key: ==AES32==onXRqpVtlebXW+dN5atvjpZGuyNH8pzkAD7tx7diCj9rnByX9+BxlESV1ehoo7D7BtoDCDf73uLYVqXDQvdOq5JoL9AAFdIr
  region: us-east-1
  sts_account: 122130270846
  sts_role: rai
  sts_role_duration_seconds: 15m
store:
  provider: s3
  base_url: http://s3.amazonaws.com
  acl: public-read
client:
  name: rai
  upload_bucket: files.rai-project.com
  bucket: userdata
  build_file: rai_build
  submit_requirements:
    - report.pdf
  job_queue_name: rai_amd64
  analytics_key: UA-109527708-1
database:
  endpoints:
    - ec2-54-167-107-36.compute-1.amazonaws.com
  username: rai-client
  password: ==AES32==PT1BRVMzMj09xQ/h9OZv0UwoqpG3AL30LxJPP5fjgn4STQfGGAAqLGAYtppTkt6r3gZvByk=
auth:
  provider: auth0
  domain: raiproject.auth0.com
  client_id: ==AES32==59Eg6+hFDfkoeZCkQvSUo0sgCsHcu1B9MoGgANkwyzJqgtVfQr7IG6iY+awG8abQPUmnaaAqJrYfbtxO
  client_secret: ==AES32==2pOhrh3oRAs+o6h1Z7kcM4w6LpFjL67+j2vBTMGpS91jtBO42wKGjkIUTCtqUukMy2K/5VmzL125YcuPnwiVbZiwXTrmr8O/gW8H/DOGEWCjI5dqcaHhIsMFVEWT5GNbw1/moxb4sF4=
pubsub:
  endpoints:
    - pubsub.rai-project.com:6379
  password: ==AES32==SnY+X9yvTpvVRWo+hqq1Bjup8vvYEtDURcsO2w==
logger:
  level: debug
  hooks:
    - graylog
graylog:
  address: 34.199.189.82
  port: 12201
